# KubeVirt SMBIOS hook sidecar
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  running: false
  template:
    metadata:
      annotations:
        hooks.kubevirt.io/hookSidecars: '[{"args": ["--version", "v1alpha2"], "image": "localhost:5000/kubevirt/example-hook-sidecar:arif1"}]'
        smbios.vm.kubevirt.io/baseBoardManufacturer: "Radical Edward"
      labels:
        kubevirt.io/vm: vm-cirros
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - disk:
              bus: virtio
            name: cloudinitdisk
        machine:
          type: ""
        resources:
          requests:
            memory: 8G
      terminationGracePeriodSeconds: 0
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: ubuntu2
      - name: cloudinitdisk
        cloudInitConfigDrive:
          userData: |
            #!/bin/bash
            sudo adduser -U -m ubuntu
            echo "ubuntu:ubuntu" | chpasswd
